version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Build Docker image
          command: docker build -t specialist-recommender-image .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag specialist-recommender-image "$DOCKER_USERNAME/specialist-recommender-image:latest"
            docker push "$DOCKER_USERNAME/specialist-recommender-image:latest"
