version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    executor: docker
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t specialist .

      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip

      - run:
          name: Install dependencies
          command: pip install -r specialist_recommender/requirements.txt

workflows:
  version: 2
  example-workflow:
    jobs:
      - build



