version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t specialist .
            echo "${password}" | docker login -u "${username}" --password-stdin
            docker push specialist




