version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: home/specialist_recommender

    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip

      - run:
          name: Install dependencies
          command: pip install -r home/requirements.txt
      - run:
          name: Build Docker image
          command: docker build -t specialist-recommender-image .
