version: 2.1
jobs:
  build:
    resource_class: medium
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 20.10.10
          
      - run:
          name: Build Docker image
          command: docker build -t specialist .
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u ${username} -p ${password}
            docker push specialist

workflows:
  version: 2
  example-workflow:
    jobs:
      - build





