version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/fatimzahra1/specialist_recommender/environment-variables
          username: $username
          password: $username
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
           command: |
             docker build -t specialist .
             docker login -u ${username} -p ${password}
             docker push specialist
          

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name



